#ifndef GUARD_CONSTANTS_BATTLE_SWITCH_IN_H
#define GUARD_CONSTANTS_BATTLE_SWITCH_IN_H

enum SwitchInEvents
{
    SWITCH_IN_EVENTS_ORDER_BY_SPEED,
    SWITCH_IN_EVENTS_TERA_SHIFT,
    SWITCH_IN_EVENTS_NEUTRALIZING_GAS,
    SWITCH_IN_EVENTS_UNNERVE,
    SWITCH_IN_EVENTS_UNNERVE_INNATE, // FORK: active innate Unnerve, fires after the chosen-ability Unnerve pass
    SWITCH_IN_EVENTS_FIRST_BLOCK,
    SWITCH_IN_EVENTS_FORM_CHANGE,
    SWITCH_IN_EVENTS_SECOND_BLOCK,
    SWITCH_IN_EVENTS_WHITE_HERB,
    SWITCH_IN_EVENTS_OPPORTUNIST,
    SWITCH_IN_EVENTS_MIRROR_HERB,
    SWITCH_IN_EVENTS_CLEAR_SET_VALUES,
    SWITCH_IN_EVENTS_EJECT_PACK,
    SWITCH_IN_EVENTS_COUNT,
};

enum SwitchInFirstEventBlock
{
    FIRST_EVENT_BLOCK_HEALING_WISH,
    FIRST_EVENT_BLOCK_HAZARDS,
    FIRST_EVENT_BLOCK_GENERAL_ABILITIES,
    FIRST_EVENT_BLOCK_GENERAL_ABILITIES_INNATE, // FORK: active switch-in innates (Intimidate)
    FIRST_EVENT_BLOCK_IMMUNITY_ABILITIES,
    FIRST_EVENT_BLOCK_ITEMS,
    FIRST_EVENT_BLOCK_COUNT,
};

enum SwitchInSecondEventBlock
{
    SECOND_EVENT_ABILITIES,
    SECOND_EVENT_ABILITIES_INNATE, // FORK: active switch-in innates that depend on the ally (Hospitality)
    SECOND_EVENT_BOOSTER_ENERGY,
    SECOND_EVENT_BLOCK_COUNT,
};

#endif // GUARD_CONSTANTS_BATTLE_SWITCH_IN_H
